project:
  type: website
  output-dir: ../docs
  render:
    - "*.qmd"
    - "!data/solutions/"

website:
  favicon: /img/who_favicon.png
  navbar:
    search: true
    logo: /img/who_logo.png
    left:
      - href: index.qmd
        text: Home
      - href: setup.qmd
        text: Setup
      - href: intro.qmd
        text: Intro to R
      - text: Data
        menu:
          - href: data_import.qmd
            text: "Importing"
          - href: data_clean.qmd
            text: "Cleaning"
      - text: Analysis
        menu:
          - href: task1.qmd
            text: "1. Setting up an automated report"
          - href: task2.qmd
            text: "2. Basic descriptive analyses"
          - href: task3.qmd
            text: "3. Generating interactive maps"
          - href: task4.qmd
            text: "4. Visualising transmission chains"
          - href: task5.qmd
            text: "5. Getting epidemiological parameters"
          - href: task6.qmd
            text: "6. Estimating disease severity"
          - href: task7.qmd
            text: "7. Estimating the reproduction number"
          - href: task8.qmd
            text: "8. Nowcasting epidemiological data"
          - href: task9.qmd
            text: "9. Forecasting cases and deaths"
          - href: task10.qmd
            text: "10. Simulating disease transmission"
    right:
      - href: https://collaboratory.who.int/forum/c/afro-ca-cop/
        text: '<img src="/img/collaboratory_logo.png" height="24px" style="vertical-align: middle; margin-right: 0.25em;">'

link-external: true
link-external-icon: true
link-external-newwindow: true

format:
  html:
    theme: cosmo
    toc: true
    css: styles.css
    download-links: true
    execute:
      warning: false
      message: false

